#!/bin/bash

mydir=`dirname $0`
cd $mydir

ts=`date +"%s"`
dt=`date +"%Y%m%d-%H%M"`
tlTemp=/tmp/timeLapse
source .config

./wyzecapture

[ ! -d ${tlTemp} ] && mkdir -p ${tlTemp}
cp ${pathToFile}/${wyzeFileName} ${tlTemp}/timelapse-${ts}.jpg

# Overlay graph
#convert ${pathToFile}/${wyzeFileName} ${pathToFile}/weatherBandit.png -compose blend -define compose:args=50 -composite -set option:modulate:colorspace hsb -modulate 100,100,50 ${pathToFile}/test.png
#convert ${pathToFile}/${wyzeFileName} ${pathToFile}/weatherBandit.png -compose blend -define compose:args=50 -composite -set option:modulate:colorspace hsb -modulate 100,100,50 ${pathToFile}/test.png
#composite -compose atop -geometry -13-17 ${pathToFile}/weatherBandit.png ${pathToFile}/${wyzeFileName}  ${pathToFile}/test.png
#composite -transparent -gravite bottom ${pathToFile}/weatherBandit.png ${pathToFile}/${wyzeFileName}  ${pathToFile}/test.png
composite -gravity South ${pathToFile}/weatherBandit.png ${pathToFile}/${wyzeFileName} -define filter:option=average -resize 800x600 ${pathToFile}/test.png

## add morning and evening detection to trigger this
## frame = black and files>48 (4hr) : run ffmpeg
## frame = black and only file (3?) : delete
fc=`ls ${tlTemp}/timelapse-*.jpg | wc -l`
br=`./brightness` 

echo Files $fc brightness $br > /tmp/timelapseStatus.log

# morning means more than 3 bright pics
if [ $br -le 45 -a $fc -le 3 ]
then
	rm -f ${tlTemp}/timelapse-*.jpg
fi

# evening means low brightness and pleanty of pictures
if [ $br -le 45 -a $fc -ge 50 ]
then
	cat ${tlTemp}/*.jpg | ffmpeg -f image2pipe -r 1 -vcodec mjpeg -i - -vcodec libx264 ${tlTemp}/timelapse-${dt}.mp4
	mv ${tlTemp}/timelapse-${dt}.mp4 ${pathToFile}/
	rm -f ${tlTemp}/timelapse-*.jpg 
fi

# overlay plot on the video
 
