#!/bin/bash

mydir=`dirname $0`
cd $mydir

force=0
[ "$1" = "-f" ] && force=1

ts=`date +"%s"`
dt=`date +"%Y%m%d-%H%M"`
source .config

./wyzecapture

[ ! -d ${tlTemp} ] && mkdir -p ${tlTemp}

## add morning and evening detection to trigger things
## frame = black and files>48 (4hr) : run ffmpeg
## frame = black and only file (3?) : delete
fc=`ls ${tlTemp}/timelapse-*.jpg | wc -l`
br=`./brightness` 
WEATHERSTAT="`grep ,2, archivedCSV/\`ls archivedCSV/|tail -1\` |tail -1|perl -pe 's/^.*,(.*?),(.*?)$/\1C\n\2%/'`"
INDOORSTAT="`grep ,4, archivedCSV/\`ls archivedCSV/|tail -1\` |tail -1|perl -pe 's/^.*,(.*?),(.*?)$/\1C\n\2%/'`"

echo Files $fc brightness $br > /tmp/timelapseStatus.log

cp ${pathToFile}/${wyzeFileName} ${tlTemp}/timelapse-${ts}.jpg

# Overlay graph
# overlay plot on the video
#composite -gravity South ${pathToFile}/weatherBandit.png ${pathToFile}/${wyzeFileName} -define filter:option=average -resize 800x600 ${pathToFile}/test.png
nice convert ${pathToFile}/${wyzeFileName} -gravity SouthWest -transparent-color white -geometry 1600x700 ${pathToFile}/overlay-graph.png -compose ModulusSubtract -define compose:args=30 -composite -set option:modulate:colorspace hsb -background none -resize 1024x768 -font helvetica -fill darkblue -pointsize 36 -draw "text 900,500 '$WEATHERSTAT'" -font helvetica -fill orange -pointsize 24 -draw "text 900,450 '$INDOORSTAT'" ${tlTemp}/timelapse-${ts}.jpg


cp ${tlTemp}/timelapse-${ts}.jpg ${pathToFile}/${timelapse}

if [ $br -eq -1 -a $force -ne 1 ]
then
	echo No image from camera. Bailing out..
	exit -1
fi

# morning means more than 3 bright pics
if [ $br -le 45 -a $fc -le 3 ]
then
	rm -f ${tlTemp}/timelapse-*.jpg
fi

# evening means low brightness and pleanty of pictures
if [ $force -eq 1 -o $br -le 45 -a $fc -ge 50 ]
then
	cat ${tlTemp}/*.jpg | nice ffmpeg -f image2pipe -r 1 -vcodec mjpeg -i - -vcodec libx264 ${tlTemp}/timelapse-${dt}.mp4
	mv ${tlTemp}/timelapse-${dt}.mp4 ${pathToFile}/
	rm -f ${tlTemp}/timelapse-*.jpg 
	ls -1 ${pathToFile}/*mp4 | perl -pe 'chomp;s,.*/(.*?\.mp4),<a href=\1>\1<\/a><br>\n,' > ${pathToFile}/timelapse.html
	chmod a+r ${pathToFile}/timelapse.html
fi

 
