#!/bin/bash

source .config

## gnuplot graph
date=`date +%Y%m%d`
dateFormatted=`date -R`
aclhdr="x-amz-acl: public-read" 
aclhdrCan=`echo ${aclhdr} | perl -pe 's,\s,,g'`

for fileName in ${fileName} ${fileNameWk} ${wyzeFileName} ${timelapse} ${timelapseVideo}
do
	cT=${contentType}
	[ "${timelapseVideo}" = "${fileName}" ] && cT=${contentTypeVideo}

	echo Uploading ${fileName}  ${cT}

	## Loop body has The Magic
	relativePath="/${s3Bucket}/${fileName}"
	date=`date +%Y%m%d`
	dateFormatted=`date -R`
	relativePath="/${s3Bucket}/${fileName}"
	aclhdr="x-amz-acl: public-read" 
	aclhdrCan=`echo ${aclhdr} | perl -pe 's,\s,,g'`
	stringToSign="PUT\n\n${cT}\n${dateFormatted}\n${relativePath}"
	signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3SecretKey} -binary | base64`
	curl -X PUT -T "${pathToFile}/${fileName}" \
	-H "Host: ${s3Bucket}.s3.amazonaws.com" \
	-H "Date: ${dateFormatted}" \
	-H "Content-Type: ${cT}" \
	-H "Authorization: AWS ${s3AccessKey}:${signature}" \
	http://${s3Bucket}.s3.amazonaws.com/${fileName}

	sleep 1

	date=`date +%Y%m%d`
	dateFormatted=`date -R`
	#stringToSign="PUT\n\n${dateFormatted}\n${cT}\n${aclhdrCan}\n${relativePath}"
	stringToSign="PUT\n\n\n${dateFormatted}\n${aclhdrCan}\n${relativePath}?acl"
	signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3SecretKey} -binary | base64`
	curl -X PUT \
	-H "Host: ${s3Bucket}.s3.amazonaws.com" \
	-H "${aclhdr}" \
	-H "Date: ${dateFormatted}" \
	-H "Authorization: AWS ${s3AccessKey}:${signature}" \
	http://${s3Bucket}.s3.amazonaws.com/${fileName}?acl
	sleep 1
done
