#!/bin/bash

source .config

touch ${pathToFile}/${wyzeFileName}
fs=0
fs=`stat --printf="%s" ${pathToFile}/${wyzeFileName}`
retry=$maxRetry

[ -f .wyzescanip ] && wyzeip=`cat .wyzescanip`

if [ $fs -gt $minWyzeSize -a -f ${pathToFile}/${wyzeFileName} ] 
then
	mv -f ${pathToFile}/${wyzeFileName} ${pathToFile}/prev${wyzeFileName}
fi

while [ $fs -lt $minWyzeSize -a $retry -gt 0 ]
do
	[ $retry -lt $maxRetry ] && echo Outfile too small: $(($fs / 1024)) kb. IP: $wyzeip Retries: $retry
	ffmpeg -ss 2 -i "rtsp://${wyzeuser}:${wyzepass}@${wyzeip}/live" -y -f image2 -qscale 0 -frames 1 ${pathToFile}/${wyzeFileName} 2> /tmp/wyzecapture.log
	retry=$(($retry - 1))
	fs=`stat --printf="%s" ${pathToFile}/${wyzeFileName}`
	sleep 3
done


